version: "2.4"

services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"

  product-service:
    build: ./product-service
    container_name: product-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8081:8081"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - auth-service
      - product-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "9000:9000"